version: '3.8'

volumes:
  postgres_data: { }

services:
  app:
    build: .
    ports:
      - "8000:8000"
    user: "1000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: /start.sh

  postgres:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env