# Generated by Django 4.1.2 on 2022-11-11 12:13

import django.db.models.deletion
from django.db import migrations, models

import apps.contacts.models


class Migration(migrations.Migration):

    replaces = [
        ("contacts", "0001_initial"),
        ("contacts", "0002_group_contact_group"),
        ("contacts", "0003_contact_photo"),
        ("contacts", "0004_alter_contact_photo"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relationship", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=120)),
                ("phone_number", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_auto_generated", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="contacts.group",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=apps.contacts.models.get_photo_path
                    ),
                ),
            ],
        ),
    ]
