# Generated by Django 4.1.2 on 2022-11-10 16:05

from django.db import migrations, models

import apps.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_group_contact_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=apps.contacts.models.get_contact_photo
            ),
        ),
    ]
