# Generated by Django 4.1.2 on 2022-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_group_contact_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="contacts/"),
        ),
    ]
