# Generated by Django 4.1.2 on 2022-11-15 11:10

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.users.models.get_avatar_path),
        ),
    ]
